name: GenshinCraft
version: '${project.version}'
main: com.github.raysato.genshincraft.GenshinCraft
api-version: 1.20
depend: [NBTAPI]
commands:
  skills:
    description: Opens GenshinCraft menu
    aliases: s
